# Generated by Django 4.2.4 on 2023-09-22 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('benefits', models.TextField(default=' ')),
                ('customization', models.TextField(default=' ')),
                ('category', models.CharField(choices=[('BR', 'Braclet'), ('NL', 'Neckpiece'), ('RG', 'Ring'), ('EG', 'Earrings'), ('EX', 'Exclusive'), ('CH', 'GuaSha'), ('PS', 'Peace'), ('AN', 'Anxiety'), ('DP', 'Depression'), ('HP', 'Happiness'), ('NG', 'Negativity'), ('PC', 'Peace'), ('MT', 'Motivation'), ('RD', 'Red'), ('MC', 'Multicolour'), ('TQ', 'Turquoise'), ('BL', 'Blue'), ('PK', 'Pink'), ('PL', 'Purple'), ('AT', 'Amazonite'), ('', 'Aquamarine'), ('', 'Blue Gold Stone'), ('', 'Golden Quartz'), ('', 'Green Fluorite'), ('JP', 'Jasper'), ('', 'Garnet'), ('ML', 'Malachite'), ('OP', 'Opalite'), ('RQ', 'Rose Quartz'), ('', 'Selenite'), ('', 'Green Jade'), ('RH', 'Rhodonite'), ('', 'Pyrite'), ('', 'Strawberry Quartz'), ('', ''), ('', ''), ('', ''), ('', '')], max_length=2)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
