# Generated by Django 4.2.4 on 2023-09-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(default=0, help_text='Please enter 10 digits valid Number'),
        ),
    ]
