# Generated by Django 4.2.4 on 2023-11-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('BR', 'Braclet'), ('NL', 'Neckpiece'), ('RG', 'Ring'), ('EG', 'Earrings'), ('EX', 'Exclusive'), ('CH', 'GuaSha'), ('AN', 'Anxiety'), ('DP', 'Depression'), ('HP', 'Happiness'), ('NG', 'Negativity'), ('PC', 'Peace'), ('MT', 'Motivation'), ('RD', 'Red'), ('MC', 'Multicolour'), ('GE', 'Green'), ('BL', 'Blue'), ('PK', 'Pink'), ('PL', 'Purple'), ('AT', 'Amazonite'), ('', 'Aquamarine'), ('', 'Blue Gold Stone'), ('', 'Golden Quartz'), ('', 'Green Fluorite'), ('JP', 'Jasper'), ('', 'Garnet'), ('ML', 'Malachite'), ('OP', 'Opalite'), ('RQ', 'Rose Quartz'), ('SE', 'Selenite'), ('', 'Green Jade'), ('RH', 'Rhodonite'), ('', 'Pyrite'), ('', 'Strawberry Quartz'), ('', ''), ('', ''), ('', ''), ('', '')], max_length=2),
        ),
    ]
