# Generated by Django 5.0.4 on 2024-04-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_product_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='food_category',
            field=models.CharField(choices=[('BR', 'beverage '), ('BF', 'breakfast'), ('DT', 'dessert'), ('MC', 'main course'), ('SP', 'soup'), ('CH', 'chapati')], max_length=100),
        ),
    ]
