# Generated by Django 5.0.4 on 2024-04-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_product_food_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='food_category',
            field=models.CharField(max_length=100),
        ),
    ]
